version: "3"
services:
  server:
    build: ./server
    container_name: server
    ports:
      - 5000:5000
    environment:
      - DATA_DIR=/data
      - PORT=5000
    volumes:
      - type: bind
        source: ./data
        target: /data
        bind:
          create_host_path: true
    networks:
      - backend

  client:
    build: ./client
    container_name: client
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend

networks:
  hostnet:
    name: host
    external: true
  frontend:
  backend:
