version: "3"
services:
  server:
    build: ./server
    container_name: server
    deploy:
      resources:
        limits:
          memory: 8gb
    ports:
      - 5000:5000
    environment:
      - DATA_DIR=/data
      - PORT=5000
    volumes:
      - type: bind
        source: ./data
        target: /data
        bind:
          create_host_path: true
    restart: on-failure

  client:
    build: ./client
    container_name: client
    ports:
      - 3000:3000
    restart: on-failure
